%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\Dropbox\Zwick_Data\Zwick\export\C\Zwick\testXpert
%    II\Data\Export\long break\singlePebbleIPR_batch3_3.TXT
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/06/06 15:39:43

%% Initialize variables.
filename = 'D:\Dropbox\Zwick_Data\Zwick\export\C\Zwick\testXpert II\Data\Export\long break\singlePebbleIPR_batch3_3.TXT';
delimiter = ',';
startRow = 7;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
singlePebbleIPRbatch33 = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;


plot(singlePebbleIPRbatch33(:,1),singlePebbleIPRbatch33(:,2))